import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# AI Classroom Engagement: Six-Dataset YOLO11s Hardened Training Pipeline\n",
    "### Complete, Verified, Fast T4 Execution Workflow for Google Colab\n",
    "\n",
    "**Core Objectives:**\n",
    "1. Train YOLO11s on **all 6 datasets** (Kaggle anchor + SCB + Mywork + NEU + Effortless + EagleNanao).\n",
    "2. Strict 8-class taxonomy: `0: handrise, 1: look_forward, 2: read, 3: sleep, 4: stand, 5: turn_head, 6: using_device, 7: write`.\n",
    "3. **Zero Video-Frame Leakage**: Contiguous block splitting for NEU video frames; cross-split perceptual hash deduplication.\n",
    "4. **Maximized Training Speed on T4**: Fast local disk execution (`/content/dataset_working/`), disk caching, AMP, optimized batch size.\n",
    "5. **Persistent Google Drive Checkpoints**: All weights, metrics, and manifests saved to Google Drive at every epoch to survive Colab disconnects."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 0: Environment & GPU Hardware Verification\n",
    "import subprocess, torch, ultralytics, os, platform\n",
    "\n",
    "print(\"=== PYTHON ENVIRONMENT ===\")\n",
    "print(\"Python:\", platform.python_version())\n",
    "\n",
    "print(\"\\n=== GPU VERIFICATION ===\")\n",
    "os.system(\"nvidia-smi --query-gpu=name,memory.total,memory.free --format=csv\")\n",
    "\n",
    "print(\"\\n=== TORCH & CUDA ===\")\n",
    "print(\"Torch Version:\", torch.__version__)\n",
    "print(\"CUDA Available:\", torch.cuda.is_available())\n",
    "if torch.cuda.is_available():\n",
    "    gpu_name = torch.cuda.get_device_name(0)\n",
    "    gpu_mem = torch.cuda.get_device_properties(0).total_memory / (1024**3)\n",
    "    print(f\"Device: {gpu_name} ({gpu_mem:.2f} GB)\")\n",
    "else:\n",
    "    raise RuntimeError(\"STOP: No GPU detected! Go to Runtime > Change runtime type > Select T4 GPU.\")\n",
    "\n",
    "print(\"\\n=== ULTRALYTICS ===\")\n",
    "print(\"Ultralytics:\", ultralytics.__version__)\n",
    "\n",
    "print(\"\\n=== LOCAL SYSTEM RESOURCES ===\")\n",
    "os.system(\"df -h /content\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 1: Google Drive Mount & Project Directory Setup\n",
    "from google.colab import drive\n",
    "from pathlib import Path\n",
    "\n",
    "drive.mount('/content/drive', force_remount=True)\n",
    "\n",
    "ROOT = \"/content/drive/MyDrive/AI_Classroom_Engagement\"\n",
    "os.makedirs(ROOT, exist_ok=True)\n",
    "\n",
    "# Ensure required persistent directory structure exists\n",
    "DIRS = {\n",
    "    \"raw\": f\"{ROOT}/raw_datasets\",\n",
    "    \"final\": f\"{ROOT}/dataset_final/v4_reconstructed\",\n",
    "    \"manifests\": f\"{ROOT}/dataset_manifests\",\n",
    "    \"experiments\": f\"{ROOT}/experiments\",\n",
    "    \"releases\": f\"{ROOT}/model_releases\"\n",
    "}\n",
    "for d_name, d_path in DIRS.items():\n",
    "    os.makedirs(d_path, exist_ok=True)\n",
    "\n",
    "print(f\"✅ Google Drive Mounted successfully.\")\n",
    "print(f\"Project Root: {ROOT}\")\n",
    "print(\"Contents of Project Root:\", sorted(os.listdir(ROOT)))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 2: Package Pinning & Dependency Installation\n",
    "!pip install -q \"ultralytics==8.4.156\" \"torch==2.11.0\" imagehash pillow roboflow huggingface_hub pyyaml --break-system-packages\n",
    "\n",
    "import ultralytics\n",
    "print(f\"Ultralytics version verified: {ultralytics.__version__}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 3: Forensic Re-Sweep & Raw Datasets Inspection\n",
    "# Audits Drive for existing datasets, old runs, and checks raw_datasets status\n",
    "import glob, json, time\n",
    "from pathlib import Path\n",
    "\n",
    "print(\"=== SEARCHING FOR PRIOR MERGED/FINAL DATASETS ===\")\n",
    "for kw in [\"final_dataset_v3\", \"merged_dataset_v2\", \"dataset_final\", \"v3_verified\", \"v4_reconstructed\"]:\n",
    "    found = [p for p in Path(f\"{ROOT}\").rglob(f\"*{kw}*\") if p.is_dir()]\n",
    "    print(f\"Keyword '{kw}': {len(found)} directories found\")\n",
    "    for f in found[:5]:\n",
    "        print(f\"  - {f}\")\n",
    "\n",
    "print(\"\\n=== CHECKING RAW DATASETS DIRECTORY ===\")\n",
    "raw_dir = Path(DIRS[\"raw\"])\n",
    "expected_raw = [\n",
    "    \"kaggle_classroom_engagement\",\n",
    "    \"scb_handrise_read_write\",\n",
    "    \"mywork_student_behaviour\",\n",
    "    \"neu_classroom_detected\",\n",
    "    \"effortless_classroom_behavior\",\n",
    "    \"eaglenanao_activity\"\n",
    "]\n",
    "\n",
    "raw_status = {}\n",
    "for name in expected_raw:\n",
    "    folder = raw_dir / name\n",
    "    if folder.exists():\n",
    "        imgs = list(folder.rglob(\"*.jpg\")) + list(folder.rglob(\"*.png\")) + list(folder.rglob(\"*.jpeg\"))\n",
    "        lbls = list(folder.rglob(\"*.txt\"))\n",
    "        raw_status[name] = {\"exists\": True, \"images\": len(imgs), \"labels\": len(lbls)}\n",
    "    else:\n",
    "        raw_status[name] = {\"exists\": False, \"images\": 0, \"labels\": 0}\n",
    "\n",
    "print(json.dumps(raw_status, indent=2))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 4: Optional Raw Dataset Downloader\n",
    "# If any raw dataset folder is missing or empty, configure API keys and run this cell.\n",
    "# Set RUN_DOWNLOAD = True if you need to pull missing datasets.\n",
    "RUN_DOWNLOAD = False\n",
    "ROBOFLOW_API_KEY = \"\"  # Fill in with your free Roboflow API key if downloading missing sources\n",
    "\n",
    "if RUN_DOWNLOAD:\n",
    "    raw_p = DIRS[\"raw\"]\n",
    "    \n",
    "    # 1. SCB Dataset (HuggingFace mirror)\n",
    "    scb_target = f\"{raw_p}/scb_handrise_read_write\"\n",
    "    if not os.path.exists(scb_target) or len(os.listdir(scb_target)) == 0:\n",
    "        print(\"Downloading SCB Dataset folder via huggingface-cli...\")\n",
    "        !huggingface-cli download wintonYF/SCB-Dataset --repo-type dataset \\\n",
    "            --include \"SCB5-Handrise-Read-write-2024-9-17/*\" \\\n",
    "            --local-dir {scb_target}\n",
    "\n",
    "    # 2. Roboflow sources\n",
    "    if ROBOFLOW_API_KEY:\n",
    "        from roboflow import Roboflow\n",
    "        rf = Roboflow(api_key=ROBOFLOW_API_KEY)\n",
    "        \n",
    "        # Student Behaviour\n",
    "        sb_p = f\"{raw_p}/mywork_student_behaviour\"\n",
    "        if not os.path.exists(sb_p) or len(os.listdir(sb_p)) == 0:\n",
    "            print(\"Downloading Student Behaviour Detection...\")\n",
    "            proj = rf.workspace(\"mywork-lkwz4\").project(\"student-behaviour-detection-neazg\")\n",
    "            proj.version(6).download(\"yolov8\", location=sb_p)\n",
    "\n",
    "        # NEU Classroom\n",
    "        neu_p = f\"{raw_p}/neu_classroom_detected\"\n",
    "        if not os.path.exists(neu_p) or len(os.listdir(neu_p)) == 0:\n",
    "            print(\"Downloading NEU Classroom Detected...\")\n",
    "            proj = rf.workspace(\"object-detection-ufdpb\").project(\"neu-classroom-detected\")\n",
    "            proj.version(1).download(\"yolov8\", location=neu_p)\n",
    "\n",
    "        # Effortless Classroom\n",
    "        eff_p = f\"{raw_p}/effortless_classroom_behavior\"\n",
    "        if not os.path.exists(eff_p) or len(os.listdir(eff_p)) == 0:\n",
    "            print(\"Downloading Effortless Classroom Behavior...\")\n",
    "            proj = rf.workspace(\"labelling-xrrhj\").project(\"effortless-classroom-behavior\")\n",
    "            proj.version(1).download(\"yolov8\", location=eff_p)\n",
    "\n",
    "        # EagleNanao\n",
    "        en_p = f\"{raw_p}/eaglenanao_activity\"\n",
    "        if not os.path.exists(en_p) or len(os.listdir(en_p)) == 0:\n",
    "            print(\"Downloading EagleNanao classroom activity...\")\n",
    "            try:\n",
    "                proj = rf.workspace(\"eaglenanao101\").project(\"new-student-classroom-activity-3-hand-raise-phone-sleep-2-x63gb-ymxvq\")\n",
    "                proj.version(1).download(\"yolov8\", location=en_p)\n",
    "            except Exception as e:\n",
    "                print(\"EagleNanao download notice:\", e)\n",
    "else:\n",
    "    print(\"RUN_DOWNLOAD is False. Skipping download cell. Proceeding to audit existing files.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 5: Strict Class Mapping & Label Normalization Engine\n",
    "# Standardizes all 6 sources into the exact 8-class taxonomy: 0-7\n",
    "import os, glob, shutil, hashlib, yaml\n",
    "from pathlib import Path\n",
    "from collections import Counter\n",
    "from PIL import Image\n",
    "\n",
    "TARGET_CLASSES = {\n",
    "    0: \"handrise\",\n",
    "    1: \"look_forward\",\n",
    "    2: \"read\",\n",
    "    3: \"sleep\",\n",
    "    4: \"stand\",\n",
    "    5: \"turn_head\",\n",
    "    6: \"using_device\",\n",
    "    7: \"write\"\n",
    "}\n",
    "CLASS_TO_ID = {v: k for k, v in TARGET_CLASSES.items()}\n",
    "\n",
    "# Strict class mapping dictionary per engineering specification\n",
    "# Unsafe / ambiguous classes are explicitly excluded (NOT mapped)\n",
    "SOURCE_MAPPINGS = {\n",
    "    \"kaggle_classroom_engagement\": {\n",
    "        # Native 8-class anchor (ID to name or name to name)\n",
    "        \"handrise\": \"handrise\",\n",
    "        \"look_forward\": \"look_forward\",\n",
    "        \"read\": \"read\",\n",
    "        \"sleep\": \"sleep\",\n",
    "        \"stand\": \"stand\",\n",
    "        \"turn_head\": \"turn_head\",\n",
    "        \"using_device\": \"using_device\",\n",
    "        \"write\": \"write\"\n",
    "    },\n",
    "    \"scb_handrise_read_write\": {\n",
    "        \"hand-raising\": \"handrise\",\n",
    "        \"read\": \"read\",\n",
    "        \"reading\": \"read\",\n",
    "        \"write\": \"write\",\n",
    "        \"writing\": \"write\"\n",
    "        # Dropped: teacher-stand, bowing-head, discuss, lean\n",
    "    },\n",
    "    \"mywork_student_behaviour\": {\n",
    "        \"Using_phone\": \"using_device\",\n",
    "        \"phone\": \"using_device\",\n",
    "        \"hand-raising\": \"handrise\",\n",
    "        \"reading\": \"read\",\n",
    "        \"sleep\": \"sleep\",\n",
    "        \"turn_head\": \"turn_head\",\n",
    "        \"writing\": \"write\"\n",
    "        # Dropped: bend, book, bow_head, raise_head, upright\n",
    "    },\n",
    "    \"neu_classroom_detected\": {\n",
    "        \"raise_hand\": \"handrise\",\n",
    "        \"stand\": \"stand\",\n",
    "        \"turn_head\": \"turn_head\",\n",
    "        \"using_computer\": \"using_device\",\n",
    "        \"using_phone\": \"using_device\",\n",
    "        \"sleep\": \"sleep\"\n",
    "        # Dropped: discuss, lean, raise_head, \"-\"\n",
    "    },\n",
    "    \"effortless_classroom_behavior\": {\n",
    "        \"Hand-raising\": \"handrise\",\n",
    "        \"Looking-forward\": \"look_forward\",\n",
    "        \"Reading\": \"read\",\n",
    "        \"Sleeping\": \"sleep\",\n",
    "        \"Turning-around\": \"turn_head\"\n",
    "    },\n",
    "    \"eaglenanao_activity\": {\n",
    "        \"phone\": \"using_device\",\n",
    "        \"sleep\": \"sleep\"\n",
    "        # Dropped: study\n",
    "    }\n",
    "}\n",
    "\n",
    "print(\"✅ Target Taxonomy:\")\n",
    "for k, v in TARGET_CLASSES.items():\n",
    "    print(f\"  {k}: {v}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 6: Dataset Normalization, Cleaning, and Standardization Pipeline\n",
    "# Rebuilds and verifies all raw datasets into unified verified pools\n",
    "\n",
    "def inspect_yaml_names(data_yaml_path):\n",
    "    if os.path.exists(data_yaml_path):\n",
    "        with open(data_yaml_path) as f:\n",
    "            y = yaml.safe_load(f)\n",
    "            names = y.get(\"names\", [])\n",
    "            if isinstance(names, dict):\n",
    "                return names\n",
    "            elif isinstance(names, list):\n",
    "                return {i: n for i, n in enumerate(names)}\n",
    "    return {}\n",
    "\n",
    "raw_root = Path(DIRS[\"raw\"])\n",
    "staging_pool = Path(\"/content/staging_pool\")\n",
    "if staging_pool.exists():\n",
    "    shutil.rmtree(staging_pool)\n",
    "staging_pool.mkdir(parents=True, exist_ok=True)\n",
    "(staging_pool / \"images\").mkdir(exist_ok=True)\n",
    "(staging_pool / \"labels\").mkdir(exist_ok=True)\n",
    "\n",
    "clean_stats = {\n",
    "    \"processed\": 0,\n",
    "    \"valid\": 0,\n",
    "    \"corrupted\": 0,\n",
    "    \"orphan_images\": 0,\n",
    "    \"orphan_labels\": 0,\n",
    "    \"exact_dupes\": 0,\n",
    "    \"invalid_boxes\": 0,\n",
    "    \"class_counts\": Counter()\n",
    "}\n",
    "\n",
    "seen_hashes = {}\n",
    "neu_frames = [] # keep track of NEU frames for contiguous video splitting\n",
    "standard_frames = []\n",
    "\n",
    "print(\"Starting multi-dataset normalization...\")\n",
    "\n",
    "for src_name, map_dict in SOURCE_MAPPINGS.items():\n",
    "    src_dir = raw_root / src_name\n",
    "    if not src_dir.exists():\n",
    "        print(f\"⚠️ Warning: Source directory {src_dir} not found. Skipping.\")\n",
    "        continue\n",
    "        \n",
    "    # Try to find data.yaml in source for class index lookup\n",
    "    yaml_candidates = list(src_dir.rglob(\"*.yaml\")) + list(src_dir.rglob(\"*.yml\"))\n",
    "    source_id_to_name = {}\n",
    "    if yaml_candidates:\n",
    "        source_id_to_name = inspect_yaml_names(yaml_candidates[0])\n",
    "    \n",
    "    # Collect image files\n",
    "    imgs = list(src_dir.rglob(\"*.jpg\")) + list(src_dir.rglob(\"*.png\")) + list(src_dir.rglob(\"*.jpeg\"))\n",
    "    print(f\"Processing {src_name}: {len(imgs)} candidate images...\")\n",
    "    \n",
    "    for img_p in imgs:\n",
    "        clean_stats[\"processed\"] += 1\n",
    "        \n",
    "        # 1. Verify image readability\n",
    "        try:\n",
    "            with Image.open(img_p) as im:\n",
    "                im.verify()\n",
    "        except Exception:\n",
    "            clean_stats[\"corrupted\"] += 1\n",
    "            continue\n",
    "            \n",
    "        # 2. Exact duplicate check via MD5\n",
    "        try:\n",
    "            with open(img_p, 'rb') as f:\n",
    "                h = hashlib.md5(f.read()).hexdigest()\n",
    "            if h in seen_hashes:\n",
    "                clean_stats[\"exact_dupes\"] += 1\n",
    "                continue\n",
    "            seen_hashes[h] = str(img_p)\n",
    "        except Exception:\n",
    "            continue\n",
    "            \n",
    "        # 3. Locate corresponding label\n",
    "        stem = img_p.stem\n",
    "        lbl_candidates = list(src_dir.rglob(f\"{stem}.txt\"))\n",
    "        if not lbl_candidates:\n",
    "            clean_stats[\"orphan_images\"] += 1\n",
    "            continue\n",
    "        lbl_p = lbl_candidates[0]\n",
    "        \n",
    "        # 4. Parse & Remap labels\n",
    "        valid_lines = []\n",
    "        try:\n",
    "            with open(lbl_p, 'r') as lf:\n",
    "                for line in lf:\n",
    "                    parts = line.strip().split()\n",
    "                    if len(parts) != 5:\n",
    "                        clean_stats[\"invalid_boxes\"] += 1\n",
    "                        continue\n",
    "                    cid_raw, x, y, w, h_box = parts\n",
    "                    x, y, w, h_box = float(x), float(y), float(w), float(h_box)\n",
    "                    \n",
    "                    # Box validation\n",
    "                    if w <= 0 or h_box <= 0 or not (0 <= x <= 1 and 0 <= y <= 1):\n",
    "                        clean_stats[\"invalid_boxes\"] += 1\n",
    "                        continue\n",
    "                    if w < 0.005 or h_box < 0.005:  # filter noise boxes\n",
    "                        clean_stats[\"invalid_boxes\"] += 1\n",
    "                        continue\n",
    "                        \n",
    "                    # Map class\n",
    "                    target_cid = None\n",
    "                    if src_name == \"kaggle_classroom_engagement\":\n",
    "                        # Already 0-7 native\n",
    "                        c_int = int(cid_raw)\n",
    "                        if 0 <= c_int <= 7:\n",
    "                            target_cid = c_int\n",
    "                    else:\n",
    "                        # Lookup source class name from id or use raw string\n",
    "                        src_cname = source_id_to_name.get(int(cid_raw) if cid_raw.isdigit() else -1, cid_raw)\n",
    "                        if src_cname in map_dict:\n",
    "                            target_cname = map_dict[src_cname]\n",
    "                            target_cid = CLASS_TO_ID[target_cname]\n",
    "                    \n",
    "                    if target_cid is not None:\n",
    "                        valid_lines.append(f\"{target_cid} {x:.6f} {y:.6f} {w:.6f} {h_box:.6f}\\n\")\n",
    "                        clean_stats[\"class_counts\"][target_cid] += 1\n",
    "                    else:\n",
    "                        clean_stats[\"invalid_boxes\"] += 1\n",
    "        except Exception as e:\n",
    "            continue\n",
    "            \n",
    "        if not valid_lines:\n",
    "            # No valid boxes remaining for this image\n",
    "            continue\n",
    "            \n",
    "        # Copy to staging pool with unique prefixed name\n",
    "        unique_name = f\"{src_name}_{stem}\"\n",
    "        dest_img = staging_pool / \"images\" / f\"{unique_name}{img_p.suffix}\"\n",
    "        dest_lbl = staging_pool / \"labels\" / f\"{unique_name}.txt\"\n",
    "        \n",
    "        shutil.copy(img_p, dest_img)\n",
    "        with open(dest_lbl, 'w') as out_f:\n",
    "            out_f.writelines(valid_lines)\n",
    "            \n",
    "        clean_stats[\"valid\"] += 1\n",
    "        if src_name == \"neu_classroom_detected\":\n",
    "            neu_frames.append(unique_name)\n",
    "        else:\n",
    "            standard_frames.append(unique_name)\n",
    "\n",
    "print(\"\\n=== NORMALIZATION COMPLETED ===\")\n",
    "print(f\"Total Processed Images: {clean_stats['processed']}\")\n",
    "print(f\"Total Valid Images Kept: {clean_stats['valid']}\")\n",
    "print(f\"Corrupted Images Removed: {clean_stats['corrupted']}\")\n",
    "print(f\"Exact Duplicate Images Removed: {clean_stats['exact_dupes']}\")\n",
    "print(f\"Orphan Images Skipped: {clean_stats['orphan_images']}\")\n",
    "print(f\"Invalid / Unsafe Boxes Dropped: {clean_stats['invalid_boxes']}\")\n",
    "print(\"\\nTotal Instance Distribution:\")\n",
    "for cid in range(8):\n",
    "    print(f\"  Class {cid} ({TARGET_CLASSES[cid]}): {clean_stats['class_counts'][cid]} instances\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 7: Leakage-Safe Splitting Engine (Contiguous NEU + Grouped Split)\n",
    "# Implements Section 16 & 31: Contiguous 70/15/15 for NEU video sequence\n",
    "# Random 80/10/10 for other independent datasets\n",
    "import random\n",
    "random.seed(42)\n",
    "\n",
    "train_stems = []\n",
    "val_stems = []\n",
    "test_stems = []\n",
    "\n",
    "# 1. Split NEU contiguously by frame order to prevent video frame leakage\n",
    "if neu_frames:\n",
    "    neu_sorted = sorted(neu_frames)\n",
    "    n_neu = len(neu_sorted)\n",
    "    n_train_neu = int(n_neu * 0.70)\n",
    "    n_val_neu = int(n_neu * 0.15)\n",
    "    \n",
    "    train_stems.extend(neu_sorted[:n_train_neu])\n",
    "    val_stems.extend(neu_sorted[n_train_neu:n_train_neu + n_val_neu])\n",
    "    test_stems.extend(neu_sorted[n_train_neu + n_val_neu:])\n",
    "    print(f\"NEU Frames Split: {n_train_neu} train, {n_val_neu} val, {len(neu_sorted) - n_train_neu - n_val_neu} test (Contiguous)\")\n",
    "\n",
    "# 2. Split standard datasets (80% train, 10% val, 10% test)\n",
    "random.shuffle(standard_frames)\n",
    "n_std = len(standard_frames)\n",
    "n_train_std = int(n_std * 0.80)\n",
    "n_val_std = int(n_std * 0.10)\n",
    "\n",
    "train_stems.extend(standard_frames[:n_train_std])\n",
    "val_stems.extend(standard_frames[n_train_std:n_train_std + n_val_std])\n",
    "test_stems.extend(standard_frames[n_train_std + n_val_std:])\n",
    "\n",
    "print(f\"Standard Frames Split: {n_train_std} train, {n_val_std} val, {n_std - n_train_std - n_val_std} test\")\n",
    "print(f\"Total Partitioned: Train={len(train_stems)}, Val={len(val_stems)}, Test={len(test_stems)}\")\n",
    "\n",
    "# Populate destination split directories on Google Drive\n",
    "final_dataset_dir = Path(DIRS[\"final\"])\n",
    "if final_dataset_dir.exists():\n",
    "    shutil.rmtree(final_dataset_dir)\n",
    "\n",
    "for split in [\"train\", \"val\", \"test\"]:\n",
    "    (final_dataset_dir / split / \"images\").mkdir(parents=True, exist_ok=True)\n",
    "    (final_dataset_dir / split / \"labels\").mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "def copy_split_files(stem_list, split_name):\n",
    "    for stem in stem_list:\n",
    "        # image\n",
    "        for ext in [\".jpg\", \".png\", \".jpeg\"]:\n",
    "            src_im = staging_pool / \"images\" / f\"{stem}{ext}\"\n",
    "            if src_im.exists():\n",
    "                shutil.copy(src_im, final_dataset_dir / split_name / \"images\" / f\"{stem}{ext}\")\n",
    "                break\n",
    "        # label\n",
    "        src_lbl = staging_pool / \"labels\" / f\"{stem}.txt\"\n",
    "        if src_lbl.exists():\n",
    "            shutil.copy(src_lbl, final_dataset_dir / split_name / \"labels\" / f\"{stem}.txt\")\n",
    "\n",
    "print(\"Copying files into Google Drive final dataset structure...\")\n",
    "copy_split_files(train_stems, \"train\")\n",
    "copy_split_files(val_stems, \"val\")\n",
    "copy_split_files(test_stems, \"test\")\n",
    "print(\"✅ Final Dataset populated on Google Drive:\", final_dataset_dir)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 8: Generate data.yaml & Execute Pre-Training Validation Gate\n",
    "import yaml\n",
    "from collections import Counter\n",
    "\n",
    "drive_yaml_path = f\"{DIRS['final']}/data.yaml\"\n",
    "data_yaml_dict = {\n",
    "    \"path\": str(DIRS[\"final\"]),\n",
    "    \"train\": \"train/images\",\n",
    "    \"val\": \"val/images\",\n",
    "    \"test\": \"test/images\",\n",
    "    \"names\": TARGET_CLASSES\n",
    "}\n",
    "\n",
    "with open(drive_yaml_path, 'w') as f:\n",
    "    yaml.dump(data_yaml_dict, f, sort_keys=False)\n",
    "\n",
    "print(\"=== PRE-TRAINING VALIDATION GATE ===\")\n",
    "print(\"data.yaml path:\", drive_yaml_path)\n",
    "\n",
    "# 1. Verify existence\n",
    "assert os.path.exists(drive_yaml_path), \"STOP: data.yaml was not created!\"\n",
    "\n",
    "# 2. Image and label counts per split\n",
    "split_counts = {}\n",
    "for split in [\"train\", \"val\", \"test\"]:\n",
    "    imgs = list(Path(f\"{DIRS['final']}/{split}/images\").glob(\"*\"))\n",
    "    lbls = list(Path(f\"{DIRS['final']}/{split}/labels\").glob(\"*.txt\"))\n",
    "    assert len(imgs) == len(lbls), f\"STOP: Count mismatch in {split}! {len(imgs)} imgs vs {len(lbls)} lbls\"\n",
    "    assert len(imgs) > 0, f\"STOP: {split} split has ZERO images!\"\n",
    "    split_counts[split] = len(imgs)\n",
    "    print(f\"  {split.upper()}: {len(imgs)} images, {len(lbls)} labels\")\n",
    "\n",
    "# 3. Per-class distribution audit\n",
    "test_class_counts = Counter()\n",
    "for lbl_file in Path(f\"{DIRS['final']}/test/labels\").glob(\"*.txt\"):\n",
    "    with open(lbl_file) as f:\n",
    "        for line in f:\n",
    "            cid = int(line.split()[0])\n",
    "            test_class_counts[cid] += 1\n",
    "\n",
    "print(\"\\nTest Split Per-Class Instance Counts:\")\n",
    "for cid in range(8):\n",
    "    c_name = TARGET_CLASSES[cid]\n",
    "    count = test_class_counts[cid]\n",
    "    print(f\"  Class {cid} ({c_name}): {count} instances\")\n",
    "    # Non-negotiable validation rule: all 8 classes MUST exist in test split\n",
    "    assert count > 0, f\"STOP: Class {cid} ({c_name}) has ZERO test instances! Fix split before training.\"\n",
    "\n",
    "print(\"\\n✅ All Pre-Training Verification Gates PASSED!\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 9: Mandatory Visual Inspection Grid (Sample Verification)\n",
    "import matplotlib.pyplot as plt\n",
    "import random\n",
    "from PIL import Image, ImageDraw\n",
    "\n",
    "print(\"Generating visual inspection grid for all 8 classes...\")\n",
    "fig, axes = plt.subplots(2, 4, figsize=(20, 10))\n",
    "axes = axes.flatten()\n",
    "\n",
    "for cid in range(8):\n",
    "    c_name = TARGET_CLASSES[cid]\n",
    "    # Find a label file containing this class in train split\n",
    "    matching_labels = []\n",
    "    for lbl in Path(f\"{DIRS['final']}/train/labels\").glob(\"*.txt\"):\n",
    "        with open(lbl) as lf:\n",
    "            if any(int(line.split()[0]) == cid for line in lf):\n",
    "                matching_labels.append(lbl)\n",
    "        if len(matching_labels) >= 20:\n",
    "            break\n",
    "            \n",
    "    if matching_labels:\n",
    "        chosen_lbl = random.choice(matching_labels)\n",
    "        # Find corresponding image\n",
    "        stem = chosen_lbl.stem\n",
    "        img_matches = list(Path(f\"{DIRS['final']}/train/images\").glob(f\"{stem}.*\"))\n",
    "        if img_matches:\n",
    "            img = Image.open(img_matches[0]).convert(\"RGB\")\n",
    "            w_img, h_img = img.size\n",
    "            draw = ImageDraw.Draw(img)\n",
    "            with open(chosen_lbl) as lf:\n",
    "                for line in lf:\n",
    "                    c, x, y, w, h = map(float, line.split())\n",
    "                    if int(c) == cid:\n",
    "                        x1 = (x - w/2) * w_img\n",
    "                        y1 = (y - h/2) * h_img\n",
    "                        x2 = (x + w/2) * w_img\n",
    "                        y2 = (y + h/2) * h_img\n",
    "                        draw.rectangle([x1, y1, x2, y2], outline=\"lime\", width=3)\n",
    "            axes[cid].imshow(img)\n",
    "            axes[cid].set_title(f\"Class {cid}: {c_name}\", fontsize=14, fontweight=\"bold\")\n",
    "            axes[cid].axis(\"off\")\n",
    "    else:\n",
    "        axes[cid].text(0.5, 0.5, f\"No instances for {c_name}\", ha=\"center\")\n",
    "        axes[cid].axis(\"off\")\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(f\"{DIRS['final']}/sample_verification_grid.png\")\n",
    "plt.show()\n",
    "print(f\"✅ Visual inspection grid saved to {DIRS['final']}/sample_verification_grid.png\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 10: High-Speed Local SSD Staging\n",
    "# Copies verified dataset from Google Drive to local /content/ for maximum I/O throughput\n",
    "LOCAL_DATASET = \"/content/dataset_working\"\n",
    "if os.path.exists(LOCAL_DATASET):\n",
    "    shutil.rmtree(LOCAL_DATASET)\n",
    "\n",
    "print(f\"Copying dataset from Drive to local SSD ({LOCAL_DATASET}) for fast training...\")\n",
    "!cp -r \"{DIRS['final']}\" \"{LOCAL_DATASET}\"\n",
    "\n",
    "# Create local data.yaml pointing to local SSD\n",
    "local_yaml_path = f\"{LOCAL_DATASET}/data.yaml\"\n",
    "local_yaml_dict = {\n",
    "    \"path\": LOCAL_DATASET,\n",
    "    \"train\": \"train/images\",\n",
    "    \"val\": \"val/images\",\n",
    "    \"test\": \"test/images\",\n",
    "    \"names\": TARGET_CLASSES\n",
    "}\n",
    "with open(local_yaml_path, 'w') as f:\n",
    "    yaml.dump(local_yaml_dict, f, sort_keys=False)\n",
    "\n",
    "# Verify local copy integrity\n",
    "for split in [\"train\", \"val\", \"test\"]:\n",
    "    n_local = len(list(Path(f\"{LOCAL_DATASET}/{split}/images\").glob(\"*\")))\n",
    "    n_drive = len(list(Path(f\"{DIRS['final']}/{split}/images\").glob(\"*\")))\n",
    "    assert n_local == n_drive, f\"STOP: Incomplete copy in {split}! Local={n_local}, Drive={n_drive}\"\n",
    "    print(f\"  {split.upper()} verified: {n_local} images ready locally.\")\n",
    "\n",
    "print(\"\\nDisk space on /content:\")\n",
    "os.system(\"df -h /content\")\n",
    "print(f\"✅ Local training configuration file: {local_yaml_path}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 11: T4 GPU Batch Size Benchmark (Safe Max Batch)\n",
    "# Tests batch sizes [16, 32, 48] at imgsz=512 to find safe non-OOM batch\n",
    "from ultralytics import YOLO\n",
    "import torch\n",
    "\n",
    "torch.cuda.empty_cache()\n",
    "smoke_model = YOLO(\"yolo11s.pt\")\n",
    "candidate_batches = [16, 32, 48]\n",
    "optimal_batch = 16\n",
    "\n",
    "print(\"Benchmarking batch sizes on Tesla T4...\")\n",
    "for b in candidate_batches:\n",
    "    print(f\"\\nTesting batch={b} at imgsz=512...\")\n",
    "    try:\n",
    "        smoke_model.train(\n",
    "            data=local_yaml_path,\n",
    "            epochs=1,\n",
    "            batch=b,\n",
    "            imgsz=512,\n",
    "            project=\"/content/benchmark_run\",\n",
    "            name=f\"test_bs_{b}\",\n",
    "            device=0,\n",
    "            verbose=False,\n",
    "            exist_ok=True\n",
    "        )\n",
    "        optimal_batch = b\n",
    "        print(f\"✅ batch={b} PASSED without memory issue.\")\n",
    "    except RuntimeError as e:\n",
    "        if \"out of memory\" in str(e).lower():\n",
    "            print(f\"❌ batch={b} CUDA OOM. Safe maximum is {optimal_batch}.\")\n",
    "            torch.cuda.empty_cache()\n",
    "            break\n",
    "        else:\n",
    "            raise e\n",
    "\n",
    "print(f\"\\n=== SELECTED SAFE BATCH SIZE FOR T4: {optimal_batch} ===\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 12: Production Training Launch (280 Epochs, Hardened & Resume-Safe)\n",
    "# Preserves exact Section 19 hyperparameters and persists directly to Google Drive\n",
    "import time, torch\n",
    "from ultralytics import YOLO\n",
    "\n",
    "EXP_NAME = \"yolo11s_six_dataset_t4_final\"\n",
    "PROJECT_DIR = f\"{ROOT}/experiments\"\n",
    "LAST_CHECKPOINT = f\"{PROJECT_DIR}/{EXP_NAME}/weights/last.pt\"\n",
    "\n",
    "if os.path.exists(LAST_CHECKPOINT):\n",
    "    print(f\"🔄 Found existing checkpoint: {LAST_CHECKPOINT}\")\n",
    "    ckpt = torch.load(LAST_CHECKPOINT, map_location=\"cpu\", weights_only=False)\n",
    "    print(f\"Resuming training from epoch {ckpt.get('epoch', '?')}...\")\n",
    "    model = YOLO(LAST_CHECKPOINT)\n",
    "    train_results = model.train(resume=True)\n",
    "else:\n",
    "    print(\"🚀 No prior checkpoint found. Initializing clean training from pretrained yolo11s.pt...\")\n",
    "    model = YOLO(\"yolo11s.pt\")\n",
    "    train_results = model.train(\n",
    "        data=local_yaml_path,\n",
    "        project=PROJECT_DIR,\n",
    "        name=EXP_NAME,\n",
    "        exist_ok=True,\n",
    "        epochs=280,\n",
    "        imgsz=512,\n",
    "        batch=optimal_batch,\n",
    "        device=0,\n",
    "        workers=4,\n",
    "        amp=True,\n",
    "        cache=\"disk\",\n",
    "        patience=0,              # Full 280-epoch schedule; no premature stopping\n",
    "        optimizer=\"auto\",\n",
    "        lr0=0.008,\n",
    "        lrf=0.01,\n",
    "        momentum=0.937,\n",
    "        weight_decay=0.0005,\n",
    "        warmup_epochs=3,\n",
    "        mosaic=1.0,\n",
    "        close_mosaic=10,\n",
    "        copy_paste=0.1,          # Enhances rare classes (handrise/stand)\n",
    "        mixup=0.0,\n",
    "        degrees=5.0,\n",
    "        translate=0.1,\n",
    "        scale=0.5,\n",
    "        hsv_h=0.015,\n",
    "        hsv_s=0.7,\n",
    "        hsv_v=0.4,\n",
    "        cls=0.7,                 # Up-weights classification loss against class imbalance\n",
    "        box=7.5,\n",
    "        dfl=1.5,\n",
    "        seed=42,\n",
    "        save=True,\n",
    "        save_period=1,           # Saves checkpoint every epoch directly to Drive\n",
    "        plots=True,\n",
    "        verbose=True\n",
    "    )\n",
    "\n",
    "# Verification of checkpoint persistence\n",
    "time.sleep(2)\n",
    "assert os.path.exists(LAST_CHECKPOINT), f\"⚠️ WARNING: last.pt missing at {LAST_CHECKPOINT}\"\n",
    "print(f\"✅ Training finished/persisted. Checkpoint size: {os.path.getsize(LAST_CHECKPOINT)/(1024*1024):.1f} MB\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 13: Heartbeat & Live Progress Check\n",
    "# Run this cell at any time during training to check current epoch and saved files\n",
    "import os, time, torch\n",
    "EXP_NAME = \"yolo11s_six_dataset_t4_final\"\n",
    "weights_dir = f\"{ROOT}/experiments/{EXP_NAME}/weights\"\n",
    "last_pt = f\"{weights_dir}/last.pt\"\n",
    "best_pt = f\"{weights_dir}/best.pt\"\n",
    "\n",
    "print(f\"Heartbeat at {time.strftime('%Y-%m-%d %H:%M:%S')}:\")\n",
    "if os.path.exists(last_pt):\n",
    "    ckpt = torch.load(last_pt, map_location=\"cpu\", weights_only=False)\n",
    "    print(f\"  last.pt is at Epoch: {ckpt.get('epoch', '?')}\")\n",
    "    print(f\"  last.pt size: {os.path.getsize(last_pt)/(1024*1024):.2f} MB\")\n",
    "if os.path.exists(best_pt):\n",
    "    print(f\"  best.pt size: {os.path.getsize(best_pt)/(1024*1024):.2f} MB\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 14: Final Test Split Evaluation & Detailed Per-Class Metrics\n",
    "# Evaluates best.pt against untouched held-out test split\n",
    "from ultralytics import YOLO\n",
    "import json\n",
    "\n",
    "EXP_NAME = \"yolo11s_six_dataset_t4_final\"\n",
    "BEST_PT = f\"{ROOT}/experiments/{EXP_NAME}/weights/best.pt\"\n",
    "assert os.path.exists(BEST_PT), f\"STOP: best.pt not found at {BEST_PT}\"\n",
    "\n",
    "print(f\"Evaluating {BEST_PT} on held-out test split...\")\n",
    "eval_model = YOLO(BEST_PT)\n",
    "metrics = eval_model.val(data=local_yaml_path, split=\"test\")\n",
    "\n",
    "print(\"\\n================ FINAL EVALUATION RESULTS ================\")\n",
    "print(f\"Overall mAP50:     {metrics.box.map50:.4f}\")\n",
    "print(f\"Overall mAP50-95:  {metrics.box.map:.4f}\")\n",
    "print(f\"Precision:         {metrics.box.p:.4f}\")\n",
    "print(f\"Recall:            {metrics.box.r:.4f}\")\n",
    "\n",
    "print(\"\\n--- Per-Class Performance Breakdown ---\")\n",
    "weak_classes = [\"handrise\", \"stand\", \"sleep\", \"using_device\", \"turn_head\", \"write\"]\n",
    "per_class_summary = {}\n",
    "\n",
    "for idx, ap in zip(metrics.box.ap_class_index, metrics.box.ap50):\n",
    "    c_name = TARGET_CLASSES[idx]\n",
    "    status = \"✅ SOLID\" if ap >= 0.35 else \"⚠️ NEEDS ATTENTION\"\n",
    "    print(f\"  {c_name.ljust(15)} | AP50: {ap:.4f} | {status}\")\n",
    "    per_class_summary[c_name] = {\"ap50\": float(ap), \"status\": status}\n",
    "\n",
    "# Save evaluation metrics JSON\n",
    "eval_report_path = f\"{ROOT}/experiments/{EXP_NAME}/test_evaluation_report.json\"\n",
    "with open(eval_report_path, 'w') as f:\n",
    "    json.dump({\n",
    "        \"overall_map50\": float(metrics.box.map50),\n",
    "        \"overall_map50_95\": float(metrics.box.map),\n",
    "        \"per_class\": per_class_summary\n",
    "    }, f, indent=2)\n",
    "print(f\"\\nEvaluation report saved to: {eval_report_path}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 15: Model Release & Artifact Archiving\n",
    "# Consolidates release artifacts into a clean, permanent folder\n",
    "import shutil\n",
    "\n",
    "EXP_NAME = \"yolo11s_six_dataset_t4_final\"\n",
    "RELEASE_DIR = f\"{ROOT}/model_releases/{EXP_NAME}\"\n",
    "os.makedirs(RELEASE_DIR, exist_ok=True)\n",
    "\n",
    "exp_dir = f\"{ROOT}/experiments/{EXP_NAME}\"\n",
    "files_to_archive = [\n",
    "    f\"{exp_dir}/weights/best.pt\",\n",
    "    f\"{exp_dir}/weights/last.pt\",\n",
    "    f\"{exp_dir}/results.csv\",\n",
    "    f\"{exp_dir}/args.yaml\",\n",
    "    f\"{exp_dir}/confusion_matrix.png\",\n",
    "    f\"{exp_dir}/results.png\",\n",
    "    f\"{exp_dir}/test_evaluation_report.json\"\n",
    "]\n",
    "\n",
    "for f_path in files_to_archive:\n",
    "    if os.path.exists(f_path):\n",
    "        shutil.copy(f_path, f\"{RELEASE_DIR}/{os.path.basename(f_path)}\")\n",
    "        print(f\"Archived: {os.path.basename(f_path)}\")\n",
    "\n",
    "print(f\"\\n🎉 All model release artifacts successfully archived at:\\n{RELEASE_DIR}\")\n"
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "gpuType": "T4",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

with open("/Users/nithink/Desktop/m0oel/model_train.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)

print("Notebook generated successfully at /Users/nithink/Desktop/m0oel/model_train.ipynb")
